from django.conf.urls.defaults import patterns

urlpatterns = patterns('',
    (r'(\d+)/node/(\d+)/$', 'graph.views.node_info'),
    (r'(\d+)/node/(\d+)/add_property/$',
        'graph.views.node_property',
        {'action': 'add'}),
    (r'(\d+)/node/(\d+)/modify_property/$',
        'graph.views.node_property',
        {'action': 'modify'}),
    (r'(\d+)/node/(\d+)/delete_property/$',
        'graph.views.node_property',
        {'action': 'delete'}),
    (r'(\d+)/node/(\d+)/delete_node/$', 'graph.views.delete_node'),
    (r'(\d+)/relation/(\d+)/(\w+)/(\d+)/$', 'graph.views.relation_info'),
    (r'(\d+)/relation/(\d+)/(\w+)/(\d+)/add_property/$',
        'graph.views.relation_property',
        {'action':'add'}),
    (r'(\d+)/relation/(\d+)/(\w+)/(\d+)/modify_property/$',
        'graph.views.relation_property',
        {'action': 'modify'}),
    (r'(\d+)/relation/(\d+)/(\w+)/(\d+)/delete_property/$',
        'graph.views.relation_property',
        {'action': 'delete'}),
    (r'(\d+)/search_node/$', 'graph.views.search_node'),
    (r'^$', 'graph.views.index'),
    (r'(\d+)/$', 'graph.views.editor'),
)
