from django.conf.urls.defaults import patterns, url

urlpatterns = patterns('',
    (r'(\d+)/node/(\d+)/$', 'graph.views.node_info'),
    (r'(\d+)/node/(\d+)/(\d+)/$', 'graph.views.node_info'),
    (r'(\d+)/relationship/(\d+)/$', 'graph.views.relation_info'),
    (r'(\d+)/node/(\d+)/visualize/$', 'graph.views.visualize'),
    (r'(\d+)/node/expand_node/$', 'graph.views.expand_node'),
    (r'(\d+)/node/open_node_info/$', 'graph.views.open_node_info'),
    (r'(\d+)/node/(\d+)/add_property/$',
        'graph.views.node_property',
        {'action': 'add'}),
    (r'(\d+)/node/(\d+)/modify_property/$',
        'graph.views.node_property',
        {'action': 'modify'}),
    (r'(\d+)/node/(\d+)/delete_property/$',
        'graph.views.node_property',
        {'action': 'delete'}),
    (r'(\d+)/node/(\d+)/add_media/$', 'graph.views.add_media'),
    (r'(\d+)/node/(\d+)/add_media_link/$', 'graph.views.add_media_link'),
    (r'(\d+)/node/(\d+)/create_raw_relationship/$',
        'graph.views.create_raw_relationship'),
    (r'(\d+)/node/(\d+)/delete_node/$', 'graph.views.delete_node'),
    (r'(\d+)/node/(\d+)/delete_relationship/(\d+)/(\d+)/$',
        'graph.views.delete_relationship'),
    (r'(\d+)/relationship/(\d+)/add_property/$',
        'graph.views.relation_property',
        {'action': 'add'}),
    (r'(\d+)/relationship/(\d+)/modify_property/$',
        'graph.views.relation_property',
        {'action': 'modify'}),
    (r'(\d+)/relationship/(\d+)/delete_property/$',
        'graph.views.relation_property',
        {'action': 'delete'}),
    (r'(\d+)/search_nodes_by_field/(\w+)/(\w+)/$',
        'graph.views.search_nodes_by_field'),
    (r'(\d+)/search_relationships_by_field/(\w+)/([\w-]+)/$',
        'graph.views.search_relationships_by_field'),
    (r'(\d+)/get_autocompletion_objects/$',
        'graph.views.get_autocompletion_objects'),
    (r'(\d+)/search_node/$', 'graph.views.search_node'),
    (r'^$', 'graph.views.index'),
    (r'(\d+)/search_results/$', 'graph.views.search_results'),
    (r'(\d+)/import_manager/$', 'graph.views.import_manager'),
    (r'(\d+)/add_node_ajax/$', 'graph.views.add_node_ajax'),
    (r'(\d+)/add_relationship_ajax/$', 'graph.views.add_relationship_ajax'),
    (r'(\d+)/visualize_all/$', 'graph.views.visualize_all'),
    (r'json_to_gexf/(.+)/$', 'graph.views.json_to_gexf'),
    (r'(\d+)/export_to_gml/$', 'graph.views.export_to_gml'),
    (r'(\d+)/export_to_gexf/$', 'graph.views.export_to_gexf'),

    # Graph data
    url(r'graph/(\d+)/data/$', 'graph.views.search_node', name="graph_data"),

    # Edit graph data
    url(r'graph/(\d+)/data/node/(\w+)/add/$', 'graph.views.data_node_add',
        name="data_node_add"),
#    url(r'graph/(\d+)/data/node/(\d+)/edit/(\d+)/$',
#        'graph.views.data_node_edit',
#        name="data_node_edit"),
)
